import usePageRender from "@/hooks/usePageRender";
import { GlobalStyle } from "@/styles/global-styled";
import { Flex } from "astarva-ui";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const { isReadyMounted } = usePageRender();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex>
          <GlobalStyle />
          {isReadyMounted && <Component {...pageProps} />}
        </Flex>
      </main>
    </>
  );
}
